name: Build and Deploy

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag for release (e.g., v1.0.0)'
        required: true

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: |
          docker build . --file Dockerfile -t togattafudo/welcome:${{ github.event.inputs.tag }} -t togattafudo/welcome:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: togattafudo
          password: g00Dr00T2015!!

      - name: Push Docker image to Docker Hub
        run: |
          docker push togattafudo/welcome:${{ github.event.inputs.tag }}
          docker push togattafudo/welcome:latest
